### ISSUE TITLE
Feature request: max lines

### ISSUE THREAD

**Issue by jadell** [viralpatel/jquery.shorten#13]
It would be great to configure how many lines of text to show, if there are newlines in the text.

For example, if the total content length is less than the showChars, but there are newlines and I only want to see the first line, then a more link to show the remaining lines.

**Comment by holtkamp** [comment]
+1, a use case is when list (of features / functionality) is used for articles in a webshop and only a certain amount of lines should be displayed by default, lets say '10'.

**Comment by freeQman** [comment]
I added lines function for my req. but I dont know how to commit here, or there is other way to do it...., maybe some one can help me.....

**Comment by holtkamp** [comment]
You can simply directly edit the source code of the https://github.com/viralpatel/jquery.shorten/blob/master/src/jquery.shorten.js file using the GitHub website (use the 'pencil' icon). 

When saving the file, GitHub will automatically fork (create a copy) of the code to your account and open a Pull Request to the original author. 

When the autor accepts your Pull Request, your changes will be merged into the master branch.

Also see: https://help.github.com/articles/editing-files-in-your-repository/

**Comment by freeQman** [comment]
dear holtkamp 
thank u for help, I committed my code smoothly ~

**Comment by holtkamp** [comment]
Ok, nice. 

The thing you missed to do is create a Pull Request, that way you ask the maintainer of the library to adopt your code in his branch. 

I did that for you now: https://github.com/viralpatel/jquery.shorten/pull/21

**Comment by freeQman** [comment]
oops ...... missed........
anywhere ,  thank u for helping me a lot  'holtkamp'  ^_^
